### PR TITLE
Use tibble:::as_data_frame.matrix()

### LINKED ISSUE #131: Use as_data_frame from dplyr
instead of matrixToDataframe

### PR DESCRIPTION
**Pull request by krlmlr**
- remove redundant matrixToDataFrame()
- explicitly import tibble

Fixes #131.

### CODE REVIEW

**Comment by hadley** [comment]
Maybe import `data_frame()` too? It's used a lot in the tests.

**Comment by hadley** [comment]
And then we can drop the dplyr dependency?

**Comment by krlmlr** [comment]
Not quite, tidyr uses quite a lot from dplyr.

**Comment by hadley** [comment]
Oh yeah, not sure what I was thinking.

**Comment by krlmlr** [comment]
On that note, perhaps spread and gather for SQL sources (hadley/dplyr#1753) could live here -- we have the dependency anyway, and everything can be expressed with high-level operations.

**Comment by hadley** [comment]
Yeah, that makes sense

**Comment by krlmlr** [comment]
PTAL

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
