### PR TITLE
added full_set() with examples

### PR DESCRIPTION
**Pull request by eliasdabbas**
Similar to `full_seq()` I think we can have `full_set()` which does the same but for character vectors. Two examples added for `expand()` and `complete()`

### CODE REVIEW

**Comment by hadley** [comment]
I'm not sure why you wouldn't just use `unique()`?

**Comment by eliasdabbas** [comment]
This is not to find unique values, it is to complete the data by adding implicitly missing ones, but for character vectors. 
I expanded on the example you have in the documentation, here's how it might work: 

`full_set <- function(x, vec) {
   if (any(!x %in% vec)) {
     stop("x has to be a subset of vec")
   }
  return(vec)
}

resources <- frame_data(
  ~year, ~metric, ~value,
  1999, "coal", 100,
  2001, "coal", 50,
  2001, "steel", 200
)

all_metrics <- c("aluminium", "coal", "steel") 
resources %>% complete(metric = full_set(metric, all_metrics), year)
`

**Comment by hadley** [comment]
In that case, why wouldn't you do `resources %>% complete(metric = all_metrics, year)` ?

**Comment by eliasdabbas** [comment]
Didn't think it would work. Thanks!

**Pull request closed without merging**
